### ISSUE TITLE
Needs updating with new colours and logo

### ISSUE THREAD

**Issue by jarofgreen** [OpenDataServices/odsc_default_sphinx_theme#1]
@mollieodsc to provide details here

**Comment by mollieodsc** [comment]
Thanks James

If we could remove all previous ODS colours which are being depricated, and add the monochrome logo (attached) that would be great. 

@codemacabre would appreciate your input on what it should look like!

It's likely we'll want to take closer look at RTD templates after the identity review in Q2, to bring them inline too. 

Thanks - attaching logos below. 

![Image](https://github.com/user-attachments/assets/5da5a5b7-49c3-4e7a-80c2-3912033c411c)
![Image](https://github.com/user-attachments/assets/dc5d942e-2bb8-4ae6-b267-37bbc25ee0c1)

**Comment by jarofgreen** [comment]
Currently there is a slightly pink background in the left hand bar, does someone want to pick a light grey tone instead?

**Comment by codemacabre** [comment]
@mollieodsc @jarofgreen I think we might need to add a white version of the logo too (attached, but all white so you likely can't see it), as these SVGs don't have backgrounds and will be lost when the theme switches to dark mode.

![Image](https://github.com/user-attachments/assets/0f0428af-c43a-417d-bfed-faab8eeae538)

We'll also need to change the following:

https://github.com/OpenDataServices/odsc_default_sphinx_theme/blob/9ad1a16865d40aa31e75c7938f54b3f141cc4eeb/odsc_default_sphinx_theme/theme.toml#L4-L8

to:

```toml
[options]
light_css_variables= { color-brand-primary= '#000000',  color-brand-content= '#000000',  color-background-secondary= '#ffffff',  color-sidebar-brand-text= '#000000'}
dark_css_variables= { color-brand-primary= '#ffffff',  color-brand-content= '#ffffff',  color-sidebar-brand-text= '#ffffff' }
dark_logo= "ods_logo_white.svg"
light_logo="ods_logo_black.svg"
```
